{
  inputs,
  ...
}:
{
  imports = [
    ../options.nix
    ./boot.nix
    ./firewall.nix
    ./fonts.nix
    ./hardware.nix
    ./network.nix
    ./keyboard.nix
    ./jellyfin.nix
    ./qbittorrent.nix
    ./packages.nix
    ./tuigreet.nix
    ./security.nix
    ./services.nix
    ./tailscale.nix
    ./vaultwarden.nix
    ./stylix.nix
    inputs.stylix.nixosModules.stylix
    ./system.nix
    ./user.nix
    ./nopass.nix
    ./kmscon.nix
    ./syncthing.nix
    ./virtualization.nix
    ./nix.nix
    ./nix-ld.nix
    ./zram.nix
    ./xdg.nix
    ./systemEnv.nix
    ./gaming.nix
    ./archive.nix
  ];
}
