gui:
  theme:
    activeBorderColor:
      - "#286983" # pine
      - bold
    inactiveBorderColor:
      - "#9893a5" # muted
    optionsTextColor:
      - "#56949f" # foam
    selectedLineBgColor:
      - "#f4ede8" # highlight_low
    selectedRangeBgColor:
      - "#f4ede8" # highlight_low
    cherryPickedCommitBgColor:
      - "#b4637a" # love
    cherryPickedCommitFgColor:
      - "#faf4ed" # base
    unstagedChangesColor:
      - "#ea9d34" # gold
    defaultFgColor:
      - "#464261" # text
    searchingActiveBorderColor:
      - "#907aa9" # iris
