[general]
browser=xdg-open

[ui]
styleset-name=everforest-dark-hard

[statusline]

[viewer]
alternatives=text/html,text/plain

[compose]

[multipart-converters]

[filters]
text/plain=colorize
text/calendar=calendar
message/delivery-status=colorize
message/rfc822=colorize
text/html =! html
text/html=! w3m -T text/html -I UTF-8
# text/html=w3m -T text/html -dump -o display_link_number=1
.headers=colorize

[openers]
text/html=xdg-open {}
x-scheme-handler/http=xdg-open {}
x-scheme-handler/https=xdg-open {}

[hooks]

[templates]
