# change Prefix
unbind C-b
set -g prefix `
bind ` send-prefix

# 1-based indexing
set -g base-index 1
set -g pane-base-index 1

# ---- UI rice ----
# paneColor
# set -g default-terminal "${TERM}"
# set -sg terminal-overrides ",*:RGB"

# status bar
set -g status-style bg=black,fg=white,bright
# set -g status-left ""
# set -g status-right "#[fg=black, bright]#S"

##### Window buttons color #####

# Inactive windows: cyan dot
set -g window-status-format "#[fg=cyan]●"

# Active window: red dot
set -g window-status-current-format "#[fg=red]●"

# Style (no bold, keep clean look)
set -g window-status-style nobold
set -g window-status-current-style nobold

##options
set -g renumber-windows on

# panel seperators
set -g pane-border-lines simple
set -g pane-border-style fg=white,bright
set -g pane-active-border-style fg=cyan

# set -g escape-time 0
# set -g repeat-time 1000

#keybinds
bind _ split-window -v -p 33
bind | split-window -h -p 33

##### Use hjkl for movement in tmux #####
# Pane focus (Prefix + h/j/k/l)
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Pane resizing (Prefix + H/J/K/L)
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# (Optional) Switch windows (Prefix + C-h / C-l)
# bind -r C-h previous-window
# bind -r C-l next-window

# (Optional) Copy mode uses vim keys (hjkl already work here)
setw -g mode-keys vi

bind e display-popup
