# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/e475dc38-812a-431a-b7fd-895a854159a3";
    fsType = "btrfs";
    options = [
      "subvol=root"
      "compress=zstd"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/e475dc38-812a-431a-b7fd-895a854159a3";
    fsType = "btrfs";
    options = [
      "subvol=nix"
      "compress=zstd:3"
      "noatime"
    ];
    neededForBoot = true;
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/e475dc38-812a-431a-b7fd-895a854159a3";
    fsType = "btrfs";
    options = [
      "subvol=home"
      "compress=zstd"
    ];
  };

  fileSystems."/Archive" = {
    device = "/dev/disk/by-uuid/e973dce2-7d2e-412f-ba99-722ed58dbd55";
    fsType = "btrfs";
    options = [
      "subvol=ARCHIVE"
      "compress=zstd:3"
      "noatime"
      "nofail"
    ];
  };

  fileSystems."/snapshots" = {
    device = "/dev/disk/by-uuid/e973dce2-7d2e-412f-ba99-722ed58dbd55";
    fsType = "btrfs";
    options = [
      "subvol=SNAPSHOTS"
      "compress=zstd:3"
      "noatime"
      "nofail"
    ];
  };

  fileSystems."/home/hai/Storage" = {
    device = "/dev/disk/by-uuid/e973dce2-7d2e-412f-ba99-722ed58dbd55";
    fsType = "btrfs";
    options = [
      "subvol=STORAGE"
      "compress=zstd:3"
      "noatime"
      "nofail"
    ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/72DF-3BC6";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
