# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/fe8f2fd1-a89c-4056-8f84-983ace67e79e";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/fe8f2fd1-a89c-4056-8f84-983ace67e79e";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/fe8f2fd1-a89c-4056-8f84-983ace67e79e";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/Archive" =
    { device = "/dev/disk/by-uuid/e973dce2-7d2e-412f-ba99-722ed58dbd55";
      fsType = "btrfs";
      options = [ "subvol=ARCHIVE" "compress=zstd:3" "noatime" "nofail" ];
    };

  fileSystems."/snapshots" =
    { device = "/dev/disk/by-uuid/e973dce2-7d2e-412f-ba99-722ed58dbd55";
      fsType = "btrfs";
      options = [ "subvol=SNAPSHOTS" "compress=zstd:3" "noatime" "nofail" ];
    };

  fileSystems."/home/hai/Storage" =
    { device = "/dev/disk/by-uuid/e973dce2-7d2e-412f-ba99-722ed58dbd55";
      fsType = "btrfs";
      options = [ "subvol=STORAGE" "compress=zstd:3" "noatime" "nofail" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/5B91-D1A3";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
